// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.api

import com.example.petstore.model.Pet
import kotlin.uuid.Uuid
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.accept
import io.ktor.client.request.cookie
import io.ktor.client.request.header
import io.ktor.client.request.request
import io.ktor.client.request.setBody
import io.ktor.client.request.forms.FormDataContent
import io.ktor.client.request.forms.MultiPartFormDataContent
import io.ktor.client.request.forms.formData
import io.ktor.http.ContentType
import io.ktor.http.HttpMethod
import io.ktor.http.Parameters
import io.ktor.http.contentType
import io.ktor.http.encodeURLPathPart

/**
 * Manage pets and their owners' records.
 */
class PetApi(private val httpClient: HttpClient) {
    /**
     * Add a new pet
     *
     * @param pet
     */
    suspend fun addPet(
        pet: Pet,
    ): Pet =
        httpClient.request(
            "/pets",
        ) {
            method = HttpMethod.parse("POST")
            accept(ContentType.parse("application/json"))
            contentType(ContentType.parse("application/json"))
            setBody(pet)
        }.body()

    /**
     * Add a note about a pet
     *
     * @param petId
     * @param text
     * @param tags
     * @param priority
     */
    suspend fun addPetNote(
        petId: Long,
        text: String,
        tags: List<String>? = null,
        priority: Int? = null,
    ): Unit =
        httpClient.request(
            "/pets/{petId}/notes"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("POST")
            setBody(FormDataContent(Parameters.build {
                    append("text", text)
                tags?.let {
                    appendAll("tags", tags)
                }
                priority?.let {
                    append("priority", priority.toString())
                }
            }))
        }.body()

    /**
     * Remove a pet
     *
     * @param petId
     */
    suspend fun deletePet(
        petId: Long,
    ): Unit =
        httpClient.request(
            "/pets/{petId}"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("DELETE")
        }.body()

    /**
     * Find a pet by ID
     *
     * @param petId
     * @param includeDetails
     * @param xRequestID
     * @param sessionId
     * @param requestUri
     * @param requestUuid
     */
    suspend fun getPetById(
        petId: Long,
        includeDetails: Boolean? = null,
        xRequestID: String? = null,
        sessionId: String? = null,
        requestUri: String? = null,
        requestUuid: Uuid? = null,
    ): Pet =
        httpClient.request(
            "/pets/{petId}"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("GET")
            accept(ContentType.parse("application/json"))
            includeDetails?.let {
                url.parameters.append("includeDetails", includeDetails.toString())
            }
            requestUri?.let {
                url.parameters.append("requestUri", requestUri)
            }
            xRequestID?.let {
                header("X-Request-ID", xRequestID)
            }
            requestUuid?.let {
                header("requestUuid", requestUuid)
            }
            sessionId?.let {
                cookie("sessionId", sessionId)
            }
        }.body()

    /**
     * @param source
     */
    suspend fun import(
        source: String,
    ): Unit =
        httpClient.request(
            "/pets/import",
        ) {
            method = HttpMethod.parse("POST")
                url.parameters.append("source", source)
        }.body()

    /**
     * List an owner&#39;s pets
     *
     * @param ownerName
     * @param nickname
     * @param tags
     */
    suspend fun listOwnerPets(
        ownerName: String,
        nickname: String? = null,
        tags: List<String>? = null,
    ): List<Pet> =
        httpClient.request(
            "/owners/{ownerName}/pets"
                .replace("{" + "ownerName" + "}", ownerName.encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("GET")
            accept(ContentType.parse("application/json"))
            nickname?.let {
                url.parameters.append("nickname", nickname)
            }
            tags?.let {
                url.parameters.appendAll("tags", tags)
            }
        }.body()

    /**
     * List all pets
     *
     * @param pageSize
     * @param field Field to sort pets by.
     * @param `in` Where the pets live.
     */
    suspend fun listPets(
        pageSize: PageSizeListPets? = PageSizeListPets.VALUE_20,
        field: String? = null,
        `in`: InListPets? = null,
    ): List<Pet> =
        httpClient.request(
            "/pets",
        ) {
            method = HttpMethod.parse("GET")
            accept(ContentType.parse("application/json"))
            pageSize?.let {
                url.parameters.append("pageSize", pageSize.toString())
            }
            field?.let {
                url.parameters.append("field", field)
            }
            `in`?.let {
                url.parameters.append("in", `in`.toString())
            }
        }.body()

    /**
     * Update a pet&#39;s profile
     *
     * @param petId
     * @param bio
     * @param nicknames
     * @param age
     */
    suspend fun updatePetProfile(
        petId: Long,
        bio: String,
        nicknames: List<String>? = null,
        age: Int? = null,
    ): Unit =
        httpClient.request(
            "/pets/{petId}/profile"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("PUT")
            setBody(MultiPartFormDataContent(formData {
                    append("bio", bio)
                nicknames?.let {
                    nicknames.forEach { append("nicknames", it) }
                }
                age?.let {
                    append("age", age.toString())
                }
            }))
        }.body()

    enum class PageSizeListPets(val value: Long) {
        VALUE_10(10),

        VALUE_20(20),

        VALUE_50(50);

        override fun toString(): String = value.toString()
    }

    enum class InListPets(val value: String) {
        INDOORS("indoors"),

        OUTDOORS("outdoors");

        override fun toString(): String = value
    }

}
