// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.api

import com.example.petstore.model.Pet
import kotlin.uuid.Uuid
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.accept
import io.ktor.client.request.cookie
import io.ktor.client.request.header
import io.ktor.client.request.request
import io.ktor.client.request.setBody
import io.ktor.client.request.forms.FormDataContent
import io.ktor.client.request.forms.MultiPartFormDataContent
import io.ktor.client.request.forms.formData
import io.ktor.http.ContentType
import io.ktor.http.HttpMethod
import io.ktor.http.Parameters
import io.ktor.http.contentType
import io.ktor.http.encodeURLPathPart

class PetApi(private val httpClient: HttpClient) {
    /**
     * Add a new pet
     * @param pet 
     */
    suspend fun addPet(
        pet: Pet?,
    ): Pet =
        httpClient.request(
            "/pets",
        ) {
            method = HttpMethod.parse("POST")
            accept(ContentType.parse("application/json"))
            contentType(ContentType.parse("application/json"))
            setBody(pet)
        }.body()

    /**
     * Remove a pet
     * @param petId 
     */
    suspend fun deletePet(
        petId: Long,
    ): Unit =
        httpClient.request(
            "/pets/{petId}"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("DELETE")
        }.body()

    /**
     * Find a pet by ID
     * @param petId 
     * @param includeDetails 
     * @param xRequestID 
     * @param sessionId 
     * @param requestUri 
     * @param requestUuid 
     */
    suspend fun getPetById(
        petId: Long,
        includeDetails: Boolean? = null,
        xRequestID: String? = null,
        sessionId: String? = null,
        requestUri: String? = null,
        requestUuid: Uuid? = null,
    ): Pet =
        httpClient.request(
            "/pets/{petId}"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("GET")
            accept(ContentType.parse("application/json"))
            includeDetails?.let {
                url.parameters.append("includeDetails", includeDetails.toString())
            }
            requestUri?.let {
                url.parameters.append("requestUri", requestUri.toString())
            }
            xRequestID?.let {
                header("X-Request-ID", xRequestID)
            }
            requestUuid?.let {
                header("requestUuid", requestUuid)
            }
            sessionId?.let {
                cookie("sessionId", sessionId)
            }
        }.body()

    /**
     * List all pets
     */
    suspend fun listPets(
    ): List<Pet> =
        httpClient.request(
            "/pets",
        ) {
            method = HttpMethod.parse("GET")
            accept(ContentType.parse("application/json"))
        }.body()

}
