// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.api

import com.example.petstore.model.AddPetNoteRequestMentions
import com.example.petstore.model.ListShelterPetsAgesParameter
import com.example.petstore.model.ListShelterPetsShelterParameter
import com.example.petstore.model.ListShelterPetsSpeciesParameter
import com.example.petstore.model.Pet
import com.example.petstore.model.PetReference
import com.example.petstore.model.Status
import kotlin.uuid.Uuid
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.accept
import io.ktor.client.request.cookie
import io.ktor.client.request.header
import io.ktor.client.request.request
import io.ktor.client.request.setBody
import io.ktor.client.request.forms.FormDataContent
import io.ktor.client.request.forms.MultiPartFormDataContent
import io.ktor.client.request.forms.formData
import io.ktor.http.ContentType
import io.ktor.http.HttpMethod
import io.ktor.http.Parameters
import io.ktor.http.contentType
import io.ktor.http.encodeURLPathPart

/**
 * Manage pets and their owners' records.
 */
class PetApi(private val httpClient: HttpClient) {
    /**
     * Add a new pet
     *
     * @param pet
     */
    suspend fun addPet(
        pet: Pet,
    ): Pet =
        httpClient.request(
            "/pets",
        ) {
            method = HttpMethod.parse("POST")
            accept(ContentType.parse("application/json"))
            contentType(ContentType.parse("application/json"))
            setBody(pet)
        }.body()

    /**
     * Add a note about a pet
     *
     * @param petId
     * @param text
     * @param tags
     * @param priority
     * @param relatedPet
     * @param mentions
     */
    suspend fun addPetNote(
        petId: Long,
        text: String,
        tags: List<String>? = null,
        priority: Int? = null,
        relatedPet: PetReference? = null,
        mentions: AddPetNoteRequestMentions? = null,
    ): Unit =
        httpClient.request(
            "/pets/{petId}/notes"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("POST")
            setBody(FormDataContent(Parameters.build {
                    append("text", text)
                tags?.let {
                    appendAll("tags", tags)
                }
                priority?.let {
                    append("priority", priority.toString())
                }
                relatedPet?.let {
                    appendAll("relatedPet", parameterValues(relatedPet.actualInstance))
                }
                mentions?.let {
                    appendAll("mentions", parameterValues(mentions.actualInstance))
                }
            }))
        }.body()

    /**
     * Remove a pet
     *
     * @param petId
     */
    suspend fun deletePet(
        petId: Long,
    ): Unit =
        httpClient.request(
            "/pets/{petId}"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("DELETE")
        }.body()

    /**
     * Find a pet by ID
     *
     * @param petId
     * @param includeDetails
     * @param xRequestID
     * @param sessionId
     * @param requestUri
     * @param requestUuid
     */
    suspend fun getPetById(
        petId: Long,
        includeDetails: Boolean? = null,
        xRequestID: String? = null,
        sessionId: String? = null,
        requestUri: String? = null,
        requestUuid: Uuid? = null,
    ): Pet =
        httpClient.request(
            "/pets/{petId}"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("GET")
            accept(ContentType.parse("application/json"))
            includeDetails?.let {
                url.parameters.append("includeDetails", includeDetails.toString())
            }
            requestUri?.let {
                url.parameters.append("requestUri", requestUri)
            }
            xRequestID?.let {
                header("X-Request-ID", xRequestID)
            }
            requestUuid?.let {
                header("requestUuid", requestUuid)
            }
            sessionId?.let {
                cookie("sessionId", sessionId)
            }
        }.body()

    /**
     * @param source
     */
    suspend fun import(
        source: String,
    ): Unit =
        httpClient.request(
            "/pets/import",
        ) {
            method = HttpMethod.parse("POST")
                url.parameters.append("source", source)
        }.body()

    /**
     * List an owner&#39;s pets
     *
     * @param ownerName
     * @param nickname
     * @param tags
     */
    suspend fun listOwnerPets(
        ownerName: String,
        nickname: String? = null,
        tags: List<String>? = null,
    ): List<Pet> =
        httpClient.request(
            "/owners/{ownerName}/pets"
                .replace("{" + "ownerName" + "}", ownerName.encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("GET")
            accept(ContentType.parse("application/json"))
            nickname?.let {
                url.parameters.append("nickname", nickname)
            }
            tags?.let {
                url.parameters.appendAll("tags", tags)
            }
        }.body()

    /**
     * List all pets
     *
     * @param pageSize
     * @param field Field to sort pets by.
     * @param `in` Where the pets live.
     */
    suspend fun listPets(
        pageSize: PageSizeListPets? = PageSizeListPets.VALUE_20,
        field: String? = null,
        `in`: InListPets? = null,
    ): List<Pet> =
        httpClient.request(
            "/pets",
        ) {
            method = HttpMethod.parse("GET")
            accept(ContentType.parse("application/json"))
            pageSize?.let {
                url.parameters.append("pageSize", pageSize.toString())
            }
            field?.let {
                url.parameters.append("field", field)
            }
            `in`?.let {
                url.parameters.append("in", `in`.toString())
            }
        }.body()

    /**
     * List a shelter&#39;s pets
     *
     * @param shelter The shelter&#39;s numeric ID or its name.
     * @param after The pet to continue after, by name or ID.
     * @param species One species, or several.
     * @param ages One age in years, or several.
     * @param exclude Pets to leave out, by name or ID.
     * @param status
     * @param xReferringPet
     * @param lastPet
     */
    suspend fun listShelterPets(
        shelter: ListShelterPetsShelterParameter,
        after: PetReference? = null,
        species: ListShelterPetsSpeciesParameter? = null,
        ages: ListShelterPetsAgesParameter? = null,
        exclude: List<PetReference>? = null,
        status: Status? = null,
        xReferringPet: PetReference? = null,
        lastPet: PetReference? = null,
    ): List<Pet> =
        httpClient.request(
            "/shelters/{shelter}/pets"
                .replace("{" + "shelter" + "}", parameterValues(shelter.actualInstance).joinToString(",").encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("GET")
            accept(ContentType.parse("application/json"))
            after?.let {
                url.parameters.appendAll("after", parameterValues(after.actualInstance))
            }
            species?.let {
                url.parameters.appendAll("species", parameterValues(species.actualInstance))
            }
            ages?.let {
                url.parameters.append("ages", parameterValues(ages.actualInstance).joinToString(when ("csv") {
                    "ssv" -> " "
                    "tsv" -> "\t"
                    "pipes" -> "|"
                    else -> ","
                }))
            }
            exclude?.let {
                url.parameters.appendAll("exclude", exclude.map { it.actualInstance.toString() })
            }
            status?.let {
                url.parameters.append("status", status.toString())
            }
            xReferringPet?.let {
                header("X-Referring-Pet", parameterValues(xReferringPet.actualInstance).joinToString(","))
            }
            lastPet?.let {
                cookie("lastPet", parameterValues(lastPet.actualInstance).joinToString(","))
            }
        }.body()

    /**
     * Update a pet&#39;s profile
     *
     * @param petId
     * @param bio
     * @param nicknames
     * @param age
     * @param bestFriend
     */
    suspend fun updatePetProfile(
        petId: Long,
        bio: String,
        nicknames: List<String>? = null,
        age: Int? = null,
        bestFriend: PetReference? = null,
    ): Unit =
        httpClient.request(
            "/pets/{petId}/profile"
                .replace("{" + "petId" + "}", petId.toString().encodeURLPathPart()),
        ) {
            method = HttpMethod.parse("PUT")
            setBody(MultiPartFormDataContent(formData {
                    append("bio", bio)
                nicknames?.let {
                    nicknames.forEach { append("nicknames", it) }
                }
                age?.let {
                    append("age", age.toString())
                }
                bestFriend?.let {
                    parameterValues(bestFriend.actualInstance).forEach { append("bestFriend", it) }
                }
            }))
        }.body()

    // Returns the text of the value that a union parameter holds, or of each item if the value is a collection.
    private fun parameterValues(value: Any?): List<String> =
        if (value is Collection<*>) value.map { it.toString() } else listOf(value.toString())

    enum class PageSizeListPets(val value: Long) {
        VALUE_10(10),

        VALUE_20(20),

        VALUE_50(50);

        override fun toString(): String = value.toString()
    }

    enum class InListPets(val value: String) {
        INDOORS("indoors"),

        OUTDOORS("outdoors");

        override fun toString(): String = value
    }

}
