org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.isolated-projects=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.jvmargs=-Xmx2g
kotlin.daemon.jvmargs=-Xmx1g
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
