// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param id
 */
@Serializable
data class AdoptionRecord(
    @SerialName(value = "id")
    @Required
    val id: Long,
) {


}

