// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model

import com.example.petstore.model.Listing

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param page The listing's web page.
 * @param fee
 */
@Serializable
@SerialName(value = "AdoptionListing")
data class AdoptionListing(
    /**
     * The listing's web page.
     */
    @SerialName(value = "page")
    @Required
    override val page: String,

    @SerialName(value = "fee")
    @Required
    val fee: Int,
) : Listing() {

}

