// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model

import com.example.petstore.model.Cat
import com.example.petstore.model.Dog

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An adopter chooses either a cat or a dog.
 *
 * @param adopterName Name of the person adopting the pet.
 * @param cat 
 * @param dog 
 */
@Serializable
data class AdoptionRequest (

    /**
     * Name of the person adopting the pet.
     */
    @SerialName(value = "adopterName")
    @Required
    val adopterName: String,

    @SerialName(value = "cat")
    val cat: Cat? = null,

    @SerialName(value = "dog")
    val dog: Dog? = null

) {


}

