// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model

import com.example.petstore.model.Pet
import kotlinx.serialization.json.JsonElement

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param id 
 * @param name 
 * @param barkVolume 
 */
@Serializable
@SerialName(value = "dog")
data class Dog (

    @SerialName(value = "id")
    @Required
    val id: Long,

    @SerialName(value = "name")
    @Required
    val name: String,

    @SerialName(value = "barkVolume")
    @Required
    val barkVolume: Long

) : Pet() {


}

