// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * A pet listing published on a web page.
 *
 * @param page The listing's web page.
 */
@Serializable
@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator(discriminator = "kind")
sealed class Listing {

    /**
     * The listing's web page.
     */
    @SerialName(value = "page")
    @Required
    abstract val page: String

}

