// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.StructureKind
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.serializer

/**
 * A pet name, numeric ID, or no selected pet.
 */
@Serializable(with = OptionalPetReference.OptionalPetReferenceSerializer::class)
data class OptionalPetReference(val actualInstance: Any? = null) {
    object OptionalPetReferenceSerializer : KSerializer<OptionalPetReference> {
        override val descriptor = buildClassSerialDescriptor("OptionalPetReference")

        override fun serialize(encoder: Encoder, value: OptionalPetReference) {
            val jsonEncoder = encoder as? JsonEncoder
                ?: throw SerializationException("OptionalPetReference can only be serialized with Json")
            if (value.actualInstance == null) {
                jsonEncoder.encodeJsonElement(JsonNull)
                return
            }
            val element =
                encodeCandidate<String>(jsonEncoder.json, value.actualInstance) ?:
                encodeCandidate<Long>(jsonEncoder.json, value.actualInstance) ?:
                throw SerializationException("Unsupported value for OptionalPetReference")
            select(strictJson(jsonEncoder.json), element, ignoreUnknownKeys = false)
            jsonEncoder.encodeJsonElement(element)
        }

        override fun deserialize(decoder: Decoder): OptionalPetReference {
            val jsonDecoder = decoder as? JsonDecoder
                ?: throw SerializationException("OptionalPetReference can only be deserialized with Json")
            val element = jsonDecoder.decodeJsonElement()
            val ignoreUnknownKeys = jsonDecoder.json.configuration.ignoreUnknownKeys
            return OptionalPetReference(select(strictJson(jsonDecoder.json), element, ignoreUnknownKeys))
        }

        private fun strictJson(source: Json): Json = Json(source) {
            isLenient = false
            coerceInputValues = false
            ignoreUnknownKeys = true
            explicitNulls = true
            encodeDefaults = true
        }

        private fun select(json: Json, element: JsonElement, ignoreUnknownKeys: Boolean): Any? {
            if (element == JsonNull) {
                return null
            }
            val matches = mutableListOf<Pair<Any, JsonElement>>()
            decodeCandidate<String>(json, element)?.let(matches::add)
            decodeCandidate<Long>(json, element)?.let(matches::add)
            if (matches.size != 1) {
                throw SerializationException("OptionalPetReference requires exactly one matching alternative; found ${matches.size}")
            }
            // The first match that retains the most input fields retains all of them if any match does.
            val (value, encoded) = matches.maxBy { retainedFields(element, it.second) }
            // Like regular models, drop fields only when the caller's Json ignores unknown keys.
            if (!ignoreUnknownKeys && !matchesShape(element, encoded, allowUnknownKeys = false)) {
                throw SerializationException("OptionalPetReference cannot represent this value without losing fields")
            }
            return value
        }

        private inline fun <reified T> encodeCandidate(json: Json, value: Any): JsonElement? {
            if (value !is T) return null
            val serializer = json.serializersModule.serializer<T>()
            if (!acceptsValue(serializer.descriptor, value)) return null
            // SerializationException is an IllegalArgumentException.
            return try {
                json.encodeToJsonElement(serializer, value)
            } catch (_: IllegalArgumentException) {
                null
            } catch (_: ClassCastException) {
                null
            }
        }

        private fun acceptsValue(descriptor: SerialDescriptor, value: Any?): Boolean {
            if (value == null) return descriptor.isNullable
            return when (descriptor.kind) {
                PrimitiveKind.STRING -> descriptor.serialName != "kotlin.String" || value is String
                PrimitiveKind.BOOLEAN -> descriptor.serialName != "kotlin.Boolean" || value is Boolean
                PrimitiveKind.BYTE -> descriptor.serialName != "kotlin.Byte" || value is Byte
                PrimitiveKind.SHORT -> descriptor.serialName != "kotlin.Short" || value is Short
                PrimitiveKind.INT -> descriptor.serialName != "kotlin.Int" || value is Int
                PrimitiveKind.LONG -> descriptor.serialName != "kotlin.Long" || value is Long
                PrimitiveKind.FLOAT -> descriptor.serialName != "kotlin.Float" || value is Float
                PrimitiveKind.DOUBLE -> descriptor.serialName != "kotlin.Double" || value is Double
                PrimitiveKind.CHAR -> descriptor.serialName != "kotlin.Char" || value is Char
                StructureKind.LIST -> value is Collection<*> &&
                    value.all { acceptsValue(descriptor.getElementDescriptor(0), it) }
                StructureKind.MAP -> value is Map<*, *> && value.all { (key, item) ->
                    acceptsValue(descriptor.getElementDescriptor(0), key) &&
                        acceptsValue(descriptor.getElementDescriptor(1), item)
                }
                else -> true
            }
        }

        private inline fun <reified T : Any> decodeCandidate(json: Json, element: JsonElement): Pair<Any, JsonElement>? {
            val serializer = json.serializersModule.serializer<T>()
            // Primitive serializers can throw IndexOutOfBoundsException for arrays and objects.
            if (serializer.descriptor.kind is PrimitiveKind && element !is JsonPrimitive) return null
            return try {
                val value = json.decodeFromJsonElement(serializer, element)
                val encoded = json.encodeToJsonElement(serializer, value)
                if (matchesShape(element, encoded, allowUnknownKeys = true)) value to encoded else null
            } catch (_: IllegalArgumentException) {
                null
            }
        }

        private fun matchesShape(input: JsonElement, encoded: JsonElement, allowUnknownKeys: Boolean): Boolean = when {
            input is JsonObject && encoded is JsonObject -> input.all { (key, value) ->
                encoded[key]?.let { matchesShape(value, it, allowUnknownKeys) } ?: allowUnknownKeys
            }
            input is JsonArray && encoded is JsonArray -> input.size == encoded.size &&
                input.indices.all { matchesShape(input[it], encoded[it], allowUnknownKeys) }
            input is JsonPrimitive && encoded is JsonPrimitive ->
                (input == JsonNull) == (encoded == JsonNull) && input.isString == encoded.isString
            else -> false
        }

        // Counts the input fields, at any depth, that the re-encoded value retains.
        private fun retainedFields(input: JsonElement, encoded: JsonElement): Int = when {
            input is JsonObject && encoded is JsonObject -> input.entries.sumOf { (key, value) ->
                encoded[key]?.let { retainedFields(value, it) + 1 } ?: 0
            }
            input is JsonArray && encoded is JsonArray ->
                input.zip(encoded).sumOf { (item, encodedItem) -> retainedFields(item, encodedItem) }
            else -> 0
        }
    }
}

