// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param name
 */
@Serializable
data class PetName(
    @SerialName(value = "name")
    @Required
    val name: String,
) {

}

