// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model

import com.example.petstore.model.PetRating

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param content
 * @param thumbnail
 * @param tags
 * @param rating
 */
@Serializable
data class PetPhoto(
    @SerialName(value = "content")
    @Required
    val content: ByteArray,

    @SerialName(value = "thumbnail")
    val thumbnail: String? = null,

    @SerialName(value = "tags")
    val tags: Set<String>? = null,

    @SerialName(value = "rating")
    val rating: PetRating? = null,
) {

}

