// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An availability record with arbitrary additional details.
 *
 * @param status
 */
@Serializable
data class PetRecord (

    @SerialName(value = "status")
    @Required
    val status: PetRecord.Status

) {

    /**
     * Values: AVAILABLE,PENDING
     */
    @Serializable
    enum class Status(val value: String) {
        @SerialName(value = "available")
        AVAILABLE("available"),
        @SerialName(value = "pending")
        PENDING("pending");
        override fun toString(): String = value
    }

}

