// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Values: VALUE_1,VALUE_2,VALUE_3
 */
@Serializable(with = PetRatingSerializer::class)
enum class PetRating(val value: Int) {
    VALUE_1(1),

    VALUE_2(2),

    VALUE_3(3);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): String? = if (data is PetRating) "$data" else null

        /**
         * Returns a valid [PetRating] for [data], null otherwise.
         */
        fun decode(data: Any?): PetRating? = data?.let {
            val normalizedData = "$it".lowercase()
            entries.firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

internal object PetRatingSerializer : KSerializer<PetRating> {
    override val descriptor = Int.serializer().descriptor

    override fun deserialize(decoder: Decoder): PetRating {
        val value = decoder.decodeSerializableValue(Int.serializer())
        return PetRating.entries.firstOrNull { it.value == value }
            ?: throw IllegalArgumentException("Unknown enum value: $value")
    }

    override fun serialize(encoder: Encoder, value: PetRating) {
        encoder.encodeSerializableValue(Int.serializer(), value.value)
    }
}

