// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Search by name, availability, or both.
 *
 * @param name Name to search for.
 * @param status
 * @param `for` What the pets are listed for.
 */
@Serializable
data class PetSearch(
    /**
     * Name to search for.
     */
    @SerialName(value = "name")
    val name: String? = null,

    @SerialName(value = "status")
    val status: PetSearch.Status? = null,

    /**
     * What the pets are listed for.
     */
    @SerialName(value = "for")
    val `for`: PetSearch.For? = null,
) {

    /**
     * Values: AVAILABLE,PENDING
     */
    @Serializable
    enum class Status(val value: String) {
        @SerialName(value = "available")
        AVAILABLE("available"),

        @SerialName(value = "pending")
        PENDING("pending");

        override fun toString(): String = value
    }

    /**
     * What the pets are listed for.
     *
     * Values: ADOPTION,FOSTERING
     */
    @Serializable
    enum class For(val value: String) {
        @SerialName(value = "adoption")
        ADOPTION("adoption"),

        @SerialName(value = "fostering")
        FOSTERING("fostering");

        override fun toString(): String = value
    }

}

