// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param name 
 * @param nickname 
 */
@Serializable
data class PetSummary (

    @SerialName(value = "name")
    @Required
    val name: kotlin.String,

    @SerialName(value = "nickname")
    val nickname: kotlin.String? = null

) {


}

