// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param tags 
 */
@Serializable
data class PetTags (

    @SerialName(value = "tags")
    val tags: List<PetTags.Tags>? = null

) {

    /**
     * 
     *
     * Values: FRIENDLY,SHY
     */
    @Serializable
    enum class Tags(val value: String) {
        @SerialName(value = "friendly")
        FRIENDLY("friendly"),
        @SerialName(value = "shy")
        SHY("shy");
        override fun toString(): String = value
    }

}

