// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param name
 * @param microchipId
 * @param nickname
 */
@Serializable
data class RegisteredPet(
    @SerialName(value = "name")
    @Required
    val name: String,

    @SerialName(value = "microchipId")
    @Required
    val microchipId: String,

    @SerialName(value = "nickname")
    val nickname: String? = null,
) {


}

