// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model

import com.example.petstore.model.AdoptionRecord
import com.example.petstore.model.ShelterAdoptionRecord

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param record 
 * @param archived 
 */
@Serializable
data class Shelter (

    @SerialName(value = "record")
    val record: ShelterAdoptionRecord? = null,

    @SerialName(value = "archived")
    val archived: AdoptionRecord? = null

) {


}

