// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param notes
 */
@Serializable
data class ShelterAdoptionRecord(
    @SerialName(value = "notes")
    val notes: String? = null,
) {

}

