// Generated by OpenAPI Kotlin Generator. Do not edit this file manually.

package com.example.petstore.model


import kotlinx.serialization.*
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: AVAILABLE,PENDING,SOLD
 */
@Serializable
enum class Status(val value: kotlin.String) {

    @SerialName(value = "available")
    AVAILABLE("available"),

    @SerialName(value = "pending")
    PENDING("pending"),

    @SerialName(value = "sold")
    SOLD("sold");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Status) "$data" else null

        /**
         * Returns a valid [Status] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Status? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

